/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AIFilterMessage_constants.h"



const AIFilterMessageConstants g_AIFilterMessage_constants;

AIFilterMessageConstants::AIFilterMessageConstants() {
}



