/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef AIFilterMessage_CONSTANTS_H
#define AIFilterMessage_CONSTANTS_H

#include "AIFilterMessage_types.h"



class AIFilterMessageConstants {
 public:
  AIFilterMessageConstants();

};

extern const AIFilterMessageConstants g_AIFilterMessage_constants;



#endif
